//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ProductoServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoServices.IProductoService")]
    public interface IProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/Add", ReplyAction="http://tempuri.org/IProductoService/AddResponse")]
        bool Add(SL.Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/Add", ReplyAction="http://tempuri.org/IProductoService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(SL.Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/Update", ReplyAction="http://tempuri.org/IProductoService/UpdateResponse")]
        bool Update(SL.Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/Update", ReplyAction="http://tempuri.org/IProductoService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(SL.Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/Delete", ReplyAction="http://tempuri.org/IProductoService/DeleteResponse")]
        bool Delete(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/Delete", ReplyAction="http://tempuri.org/IProductoService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/GetAll", ReplyAction="http://tempuri.org/IProductoService/GetAllResponse")]
        SL.Producto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/GetAll", ReplyAction="http://tempuri.org/IProductoService/GetAllResponse")]
        System.Threading.Tasks.Task<SL.Producto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/GetById", ReplyAction="http://tempuri.org/IProductoService/GetByIdResponse")]
        SL.Producto GetById(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/GetById", ReplyAction="http://tempuri.org/IProductoService/GetByIdResponse")]
        System.Threading.Tasks.Task<SL.Producto> GetByIdAsync(int idProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServiceChannel : PL_MVC.ProductoServices.IProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServiceClient : System.ServiceModel.ClientBase<PL_MVC.ProductoServices.IProductoService>, PL_MVC.ProductoServices.IProductoService {
        
        public ProductoServiceClient() {
        }
        
        public ProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(SL.Producto obj) {
            return base.Channel.Add(obj);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(SL.Producto obj) {
            return base.Channel.AddAsync(obj);
        }
        
        public bool Update(SL.Producto obj) {
            return base.Channel.Update(obj);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(SL.Producto obj) {
            return base.Channel.UpdateAsync(obj);
        }
        
        public bool Delete(int idProducto) {
            return base.Channel.Delete(idProducto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int idProducto) {
            return base.Channel.DeleteAsync(idProducto);
        }
        
        public SL.Producto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SL.Producto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public SL.Producto GetById(int idProducto) {
            return base.Channel.GetById(idProducto);
        }
        
        public System.Threading.Tasks.Task<SL.Producto> GetByIdAsync(int idProducto) {
            return base.Channel.GetByIdAsync(idProducto);
        }
    }
}
