//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.DepartamentoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartamentoService.IDepartamentoService")]
    public interface IDepartamentoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/Add", ReplyAction="http://tempuri.org/IDepartamentoService/AddResponse")]
        bool Add(SL.Depto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/Add", ReplyAction="http://tempuri.org/IDepartamentoService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(SL.Depto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/Update", ReplyAction="http://tempuri.org/IDepartamentoService/UpdateResponse")]
        bool Update(SL.Depto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/Update", ReplyAction="http://tempuri.org/IDepartamentoService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(SL.Depto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/Delete", ReplyAction="http://tempuri.org/IDepartamentoService/DeleteResponse")]
        bool Delete(int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/Delete", ReplyAction="http://tempuri.org/IDepartamentoService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/GetAll", ReplyAction="http://tempuri.org/IDepartamentoService/GetAllResponse")]
        SL.Depto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/GetAll", ReplyAction="http://tempuri.org/IDepartamentoService/GetAllResponse")]
        System.Threading.Tasks.Task<SL.Depto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/GetById", ReplyAction="http://tempuri.org/IDepartamentoService/GetByIdResponse")]
        SL.Depto GetById(int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoService/GetById", ReplyAction="http://tempuri.org/IDepartamentoService/GetByIdResponse")]
        System.Threading.Tasks.Task<SL.Depto> GetByIdAsync(int idDepartamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartamentoServiceChannel : PL_MVC.DepartamentoService.IDepartamentoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartamentoServiceClient : System.ServiceModel.ClientBase<PL_MVC.DepartamentoService.IDepartamentoService>, PL_MVC.DepartamentoService.IDepartamentoService {
        
        public DepartamentoServiceClient() {
        }
        
        public DepartamentoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartamentoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(SL.Depto obj) {
            return base.Channel.Add(obj);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(SL.Depto obj) {
            return base.Channel.AddAsync(obj);
        }
        
        public bool Update(SL.Depto obj) {
            return base.Channel.Update(obj);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(SL.Depto obj) {
            return base.Channel.UpdateAsync(obj);
        }
        
        public bool Delete(int idDepartamento) {
            return base.Channel.Delete(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int idDepartamento) {
            return base.Channel.DeleteAsync(idDepartamento);
        }
        
        public SL.Depto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SL.Depto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public SL.Depto GetById(int idDepartamento) {
            return base.Channel.GetById(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<SL.Depto> GetByIdAsync(int idDepartamento) {
            return base.Channel.GetByIdAsync(idDepartamento);
        }
    }
}
